"""Chromium naming UI checks against the fixed 60-byte C transport contract."""
from pathlib import Path
import functools, http.server, json, shutil, subprocess, tempfile, threading
from playwright.sync_api import sync_playwright
root=Path(__file__).resolve().parents[3]
with tempfile.TemporaryDirectory() as temp:
 out=Path(temp)
 subprocess.run([root/'node_modules/.bin/esbuild',root/'src/things/pokemon-code-red/game-text.ts','--bundle','--format=esm','--outfile='+str(out/'game-text.js')],check=True)
 (out/'index.html').write_text('''<meta name="viewport" content="width=device-width,initial-scale=1"><textarea id="outside"></textarea><div id="game" tabindex="0" style="height:160px;background:#abc"><input id="menu-field"></div><script type="module">
import {bindGameText} from './game-text.js';window.epoch=3;window.polls=0;window.frees=0;window.releases=0;window.writes=[];window.attempts=[];window.ram=new Uint8Array(60);window.v=new DataView(ram.buffer);window.reset=(session=9,text='RED')=>{ram.fill(0);ram.set(new TextEncoder().encode('CRN1'));ram[4]=1;ram[6]=1;ram[7]=7;v.setUint32(8,session,true);ram[27]=text.length;ram.set(new TextEncoder().encode(text),28)};reset();window.core={HEAPU8:new Uint8Array(256),_malloc:n=>{if(n!==76)throw Error('allocation');return 8},_free:p=>{if(p!==8)throw Error('pointer');frees++},_ejs_code_red_epoch:()=>epoch,_ejs_code_red_text_snapshot:(p,n)=>{if(n!==60)throw Error('snapshot capacity');polls++;if(!ram[6])return 0;core.HEAPU8.set(ram,p);return 1},_ejs_code_red_text_write:(e,s,q,a,p,n)=>{const text=new TextDecoder().decode(core.HEAPU8.slice(p,p+n));attempts.push([e,s,q,a,text]);if(!ram[6]||e!==epoch||s!==v.getUint32(8,true)||!q||q<=v.getUint32(20,true)||(ram[24]&&q<=v.getUint32(16,true))||(a!==1&&a!==2)||n>ram[7]||!/^[A-Za-z0-9 .,!?/\\-'" ]*$/.test(text))return 0;ram[24]=0;v.setUint32(12,s,true);v.setUint32(16,q,true);ram[25]=n;ram.fill(0,44);ram.set(core.HEAPU8.slice(p,p+n),44);ram[24]=a;writes.push([e,s,q,a,text]);return 1}};window.ack=()=>{if(ram[24]===1){ram[27]=ram[25];ram.fill(0,28,44);ram.set(ram.slice(44,44+ram[25]),28)}else if(ram[24]===2)ram[6]=0;v.setUint32(20,v.getUint32(16,true),true);ram[24]=0};window.blocked=false;window.binding=bindGameText(document.querySelector('#game'),core,()=>releases++,()=>blocked);window.ready=true;
</script>''')
 class Quiet(http.server.SimpleHTTPRequestHandler):
  def log_message(self,*_):pass
 server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Quiet,directory=temp));threading.Thread(target=server.serve_forever,daemon=True).start()
 try:
  with sync_playwright() as p:
   browser=p.chromium.launch(executable_path=shutil.which('chromium'),args=['--no-sandbox']);page=browser.new_page();url=f'http://127.0.0.1:{server.server_port}/';page.goto(url);page.wait_for_function('ready');field=page.locator('[data-name]');panel=page.locator('.code-red-text-entry');results={}
   assert field.evaluate('(e)=>e===document.activeElement');assert field.input_value()=='RED';assert page.evaluate('releases')>=1
   before=page.evaluate('polls');page.wait_for_function(f'polls>{before+1}');results['desktopFocusAnd16msPolling']=True
   field.fill('');page.keyboard.type('ABCDEFGH');assert field.input_value()=='ABCDEFG';assert page.evaluate('writes.at(-1)[4]')=='ABCDEFG';assert page.evaluate('ram[24]')==1;results['normalTypingMax7AndCoalescing']=True
   page.keyboard.press('Backspace');assert field.input_value()=='ABCDEF';assert page.evaluate('writes.at(-1)[4]')=='ABCDEF';results['backspace']=True
   page.keyboard.press('Enter');page.wait_for_timeout(60);assert page.evaluate('writes.at(-1)[3]')==1;assert page.evaluate('writes.filter(x=>x[3]===2).length')==0
   page.evaluate('ack()');page.wait_for_function('writes.at(-1)[3]===2');assert page.evaluate('writes.at(-1)[4]')=='ABCDEF';results['enterWaitsLatestAckBeforeAction2']=True
   page.evaluate('ack()');page.wait_for_function('document.querySelector(".code-red-text-entry").hidden');assert page.evaluate('document.activeElement.id')=='game';results['inactiveHidesPanelRestoresGameFocus']=True
   page.evaluate('reset(10)');page.wait_for_function('document.querySelector("[data-name]")===document.activeElement');page.keyboard.press('Escape');assert panel.is_hidden();assert page.evaluate('document.activeElement.id')=='game'
   page.keyboard.press('q');assert panel.is_visible();assert field.input_value()=='REDq';results['escapeControllerAndTypedKeyReopens']=True
   page.locator('#outside').focus();before=page.evaluate('attempts.length');page.keyboard.type('outside hello');page.keyboard.press('Backspace');assert page.locator('#outside').input_value()=='outside hell';assert page.evaluate('attempts.length')==before;results['outsideFormsUntouched']=True
   page.evaluate('reset(14)');page.wait_for_timeout(40);field.focus();page.keyboard.press('Enter');page.evaluate('ack()');page.wait_for_function('ram[24]===2');page.keyboard.press('Escape');assert page.evaluate('ram[24]')==1;page.evaluate('ack()');assert page.evaluate('ram[6]')==1;assert panel.is_hidden();results['escapeReplacesQueuedConfirmation']=True
   page.evaluate('reset(16)');page.wait_for_timeout(40);field.focus();page.keyboard.press('Enter');page.evaluate('ack()');page.wait_for_function('ram[24]===2');field.fill('BAD{');assert field.input_value()=='BAD{';assert page.evaluate('ram[24]')==1;assert page.evaluate('writes.at(-1)[4]')=='RED';assert 'Use up to 7' in page.locator('[data-name-status]').inner_text();page.keyboard.press('Escape');assert page.evaluate('ram[24]')==1;assert page.evaluate('writes.at(-1)[4]')=='RED';page.evaluate('ack()');assert page.evaluate('ram[6]')==1;assert panel.is_hidden();results['invalidEditCancelsQueuedConfirmAndEscapeUsesLastValid']=True
   page.evaluate('blocked=true');page.locator('#game').focus();before=page.evaluate('attempts.length');page.keyboard.press('z');assert page.evaluate('attempts.length')==before;assert panel.is_hidden();page.evaluate('blocked=false;reset(15)');page.wait_for_timeout(40);results['blockedMenuKeysUntouched']=True
   field.focus();field.fill('OLD');page.keyboard.press('Enter');page.evaluate('epoch++;reset(11,"NEW")');page.wait_for_timeout(60);assert field.input_value()=='NEW';assert page.evaluate('writes.filter(x=>x[0]===4&&x[3]===2).length')==0
   before=page.evaluate('writes.length');page.evaluate('epoch++;const field=document.querySelector("[data-name]");field.value="STALE";field.dispatchEvent(new Event("input",{bubbles:true}))');assert page.evaluate('writes.length')==before;page.wait_for_timeout(40);assert field.input_value()=='NEW';results['epochAndSessionResetRejectStaleWrites']=True
   field.fill('HIDDEN');page.keyboard.press('Enter');page.evaluate('Object.defineProperty(document,"hidden",{configurable:true,get:()=>true});document.dispatchEvent(new Event("visibilitychange"));ack()');before=page.evaluate('writes.length');page.wait_for_timeout(60);results['hiddenDocumentDoesNotConfirm']=page.evaluate('writes.length')==before
   page.evaluate('Object.defineProperty(document,"hidden",{configurable:true,get:()=>false});reset(12)');page.wait_for_timeout(40);page.keyboard.press('Escape');page.locator('#menu-field').focus();before=page.evaluate('attempts.length');page.keyboard.type('menu');results['insideMenuFormsUntouched']=page.locator('#menu-field').input_value()=='menu' and page.evaluate('attempts.length')==before
   page.evaluate('binding.dispose();binding.dispose()');assert panel.count()==0;assert page.evaluate('frees')==1;before=page.evaluate('polls');page.wait_for_timeout(50);assert page.evaluate('polls')==before;results['idempotentDisposeFreesAndStopsPolling']=True
   mobile=browser.new_page(has_touch=True,viewport={'width':390,'height':844});mobile.goto(url);mobile.wait_for_function('ready');assert mobile.evaluate('navigator.maxTouchPoints')>0;assert mobile.evaluate('document.activeElement.tagName')!='INPUT';mobile.locator('[data-name]').tap();mobile.keyboard.press('End');mobile.keyboard.type('XY');assert mobile.locator('[data-name]').input_value()=='REDXY';assert mobile.evaluate('writes.at(-1)[4]')=='REDXY';results['mobileTapFocusAndTyping']=True
   print(json.dumps(results,indent=2));browser.close();assert all(results.values()), 'Failed expectations: '+', '.join(k for k,v in results.items() if not v)
 finally:server.shutdown()
